name: Build project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: library_service deplay
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kr-libraryservice"
          heroku_email: "ya.the.eska@gmail.com"
          appdir: library

      - name: book_service deplay
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kr-bookservice"
          heroku_email: "ya.the.eska@gmail.com"
          appdir: book

      - name: control_service deplay
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kr-controlservice"
          heroku_email: "ya.the.eska@gmail.com"
          appdir: control

      - name: rating_service deplay
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kr-ratingservice"
          heroku_email: "ya.the.eska@gmail.com"
          appdir: rating

      - name: sessions_service deplay
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kr-sessionservice"
          heroku_email: "ya.the.eska@gmail.com"
          appdir: session

      - name: report_service deplay
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kr-reportservice"
          heroku_email: "ya.the.eska@gmail.com"
          appdir: report

      - name: gateway deplay
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kr-gateway"
          heroku_email: "ya.the.eska@gmail.com"
          appdir: gateway

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/postman-collection.json
          environment: postman/postman-heroku-environment.json
          delayRequest: 50
          reporters: cli
